name: Dependency License Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    # Run on PRs with changes to this same file
    paths: ['.github/workflows/fossa.yml']

jobs:
  fossa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run FOSSA analyze
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
