name: Checks
on:
  # Ensure GitHub actions are not run twice for same commits
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Linting
        run: npm run format:ci
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node-version: [14.18.0, '*']
        exclude:
          - os: macOS-latest
            node-version: 14.18.0
          - os: windows-latest
            node-version: 14.18.0
      fail-fast: false
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Tests
        run: npm run test:ci
      - name: Get test coverage flags
        id: test-coverage-flags
        run: |-
          os=${{ matrix.os }}
          node=$(node --version)
          echo "os=${os/-latest/}" >> $GITHUB_OUTPUT
          echo "node=node_${node/.*.*/}" >> $GITHUB_OUTPUT
        shell: bash
      - uses: codecov/codecov-action@v3
        with:
          flags: ${{ steps.test-coverage-flags.outputs.os }},${{ steps.test-coverage-flags.outputs.node }}
